version: "3.8"

services:
  n8n:
    container_name: n8n
    image: n8nio/n8n:latest
    restart: always
    environment:
      # Basic Auth
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=adminpassword

      # Host & URL
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/

      # Timezone
      - GENERIC_TIMEZONE=America/New_York
      - TZ=America/New_York

      # Optional features
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

      # PostgreSQL DB
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=pgsql
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=root
      - DB_POSTGRESDB_PASSWORD=password
      - DB_SCHEMA=public
      - DB_POSTGRESDB_SSL=false

    # Mount a volume for persistence
    volumes:
      - data:/home/node/.n8n
    ports:
      - "5678:5678"
    networks:
      - n8n
    depends_on:
      - pgsql

  pgsql:
    container_name: n8n_pgsql
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: n8n
    volumes:
      - pgsql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - n8n

volumes:
  data:
  pgsql:

networks:
  n8n:
    driver: bridge
