apiVersion: v2
name: n8n
description: "A Helm chart for deploying n8n with NGINX ingress controller on DigitalOcean Kubernetes."
version: 1.0.0  # Chart version
appVersion: "1.0.0"  # Application version (this is optional)