apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Release.Name }}-certificate"
spec:
  issuerRef:
    name: "{{ .Release.Name }}-issuer"
    kind: Issuer
    group: cert-manager.io
  dnsNames:
    - "*.{{ .Values.gateway.host }}"
  secretName: "{{ .Release.Name }}-certificate"