# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: "{{ .Release.Name }}-tls-cert"
# spec:
#   secretName: "{{ .Release.Name }}-tls-secret"   # THIS fixes the secret name
#   issuerRef:
#     name: "{{ .Release.Name }}-issuer"
#     kind: Issuer
#   commonName: "*.{{ .Values.gateway.host }}"
#   dnsNames:
#     - "*.{{ .Values.gateway.host }}"
