apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: "{{ .Release.Name }}-gateway"
  annotations:
    cert-manager.io/issuer: "{{ .Release.Name }}-issuer"
spec:
  gatewayClassName: "{{ .Release.Name }}-gatewayclass"
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
    http:
      redirect:
        statusCode: 308
        scheme: HTTPS
        port: 443
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - name: "{{ .Release.Name }}-certificate"