apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: "{{ .Release.Name }}-gateway"
  annotations:
    cert-manager.io/issuer: "{{ .Release.Name }}-issuer"
spec:
  gatewayClassName: "kong"
  listeners:
  # - name: http
  #   protocol: HTTP
  #   port: 80
  #   hostname: "{{ .Values.gateway.host }}"
  - name: https
    protocol: HTTPS
    port: 443
    hostname: "{{ .Values.gateway.host }}"
    tls:
      mode: Terminate
      certificateRefs:
      - name: "{{ .Release.Name }}-tls"