apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kong-operator-read-secrets
  namespace: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kong-operator-read-secrets
  namespace: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: controller-manager         # the Kong operator SA
  namespace: kong-system           # namespace where operator is running
roleRef:
  kind: Role
  name: kong-operator-read-secrets
  apiGroup: rbac.authorization.k8s.io
