apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - name: "{{ .Release.Name }}-http"
      port: {{ .Values.gateway.externalPort }}         # External port to expose (e.g., 80 or 443)
      targetPort: {{ .Values.gateway.internalPort }}   # The port the app listens to inside the pod
      protocol: TCP
  selector:
    app: {{ .Release.Name }}                  # Match labels from the deployment