apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: "{{ .Release.Name }}-dopplersecret"
spec:
  tokenSecret:
    name: "{{ .Release.Name }}-doppler-token-secret"
  project: {{ .Release.Name }}
  config: prod
  managedSecret:
    name: "{{ .Release.Name }}-secret-doppler"
    namespace: {{ .Release.Name }}
    type: Opaque
  resyncSeconds: 60