# Example values.yaml using portfolio data
deployment:
  replicas: 1
  image:
    repository: n8nio/n8n
    tag: 2.1.4

gateway:
  host: n8n.example.com
  internalPort: 5678

secret:
  dopplerToken: overwriteThisValue

issuer:
  email: user@email.com
  server: https://acme-v02.api.letsencrypt.org/directory
  create: true

config:
  APP_NAME: test
  REDIS_HOST: test-redis